Repository TomKlotzPro/openNetwork, pull requests merged in 2020-11, with the labels that each got.

#6 Chore: add tailwindcss and remove vuetify
  assets/tailwind.css
  layouts/default.vue
  layouts/error.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
  pages/inspire.vue
  tailwind.config.js
Labels: Ready for review

#7 Feat(front): add welcome page
  assets/css/_app.css
  assets/css/_base.css
  assets/css/tailwind.css
  assets/images/hero.svg
  assets/images/opentwk.svg
  assets/variables.scss
  components/Button.vue
  components/Footer.vue
  components/Hero.vue
  components/Logo.vue
  components/Navbar.vue
  components/ProjectCard.vue
  components/Search.vue
  components/VuetifyLogo.vue
  layouts/default.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
  pages/login.vue
  tailwind-full.config.js
  tailwind.config.js
Labels: Not ready for review, enhancement

#9 Chore(Readme) :update readme with synopsis
  README.md
Labels: documentation

#8 Feat(Front): add signup page
  assets/images/error.svg
  assets/images/info.svg
  assets/images/signup.jpg
  assets/images/success.svg
  assets/images/warning.svg
  components/Button.vue
  components/Footer.vue
  components/Hero.vue
  components/Input.vue
  components/Message.vue
  components/Navbar.vue
  components/ProjectCard.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/signup.vue
  plugins/vuelidate.js
  server/controllers/authentification/signup/post.signup.js
  server/data/users.json
  store/authentification.js
  tailwind.config.js
Labels: Ready for review, good first issue

#14 [FEAT] - Server Major Update
  middleware/auth.js
  middleware/user.js
  server/.local.server.config.example
  server/controllers/api.js
  server/controllers/auth.js
  server/controllers/authentification/login/post.login.js
  server/controllers/authentification/signup/post.signup.js
  server/controllers/category.js
  server/controllers/product.js
  server/controllers/upload.js
  server/controllers/user.js
  server/data/users.json
  server/db/index.js
  server/helpers/.helpers
  server/helpers/helper.js
  server/helpers/helperUser.js
  server/index.js
  server/keys/dev.js
  server/keys/index.js
  server/keys/prod.js
  server/middleware/upload.js
  server/models/authentification.model.js
  server/models/category.js
  server/models/product.js
  server/models/user.js
  server/routes/api.js
  server/routes/authentification.route.js
  server/routes/category.js
  server/routes/index.js
  server/routes/product.js
  server/routes/routes.js
  server/routes/user.js
  server/server.config.js
  server/server.js
  server/services/passport.js
  server/test/login/post.login.spec.js
  server/test/signup/post.signup.spec.js
  store/authentification.js
Labels: Ready for review
